#!/bin/bash

for i in parallel levelset poisson DiST geom num out misc poisson stokes navstokes levelset surfactant transport; do ./make_baseCMakeLists "$i/" > "$i/CMakeLists.txt"; cat "$i/Makefile" | ./convert.py >> "$i/CMakeLists.txt"; done
