#!/bin/bash

FOLDER=$(echo $1 | sed -e "s/\/$//")

echo -e "#CMakeLists.txt for ${FOLDER} package\n\n\n#LIBRARIES"

cd ${FOLDER}
ls *.cpp | sed -e "s/\(.*\)\.cpp/add_library($FOLDER-\1 SHARED \1)/"

echo -e "\n#EXECUTABLES"
